superfaceai/one-sdk-js

CHANGELOG.md
src/internal/providerjson.test.ts
src/internal/providerjson.ts

feat: provider name check

---

README.md

chore: mention SUPERFACE_API_URL

---

CHANGELOG.md
src/internal/interpreter/profile-parameter-validator.errors.ts
src/internal/interpreter/profile-parameter-validator.test.ts
src/internal/interpreter/profile-parameter-validator.ts

Fixes incorrect handling of non-nullable fields
#85

fix(profile-parameter-validator): Handle NonNullable fields properly

---

CHANGELOG.md

Reconstructing changelog
Because I am very bad boy and didn't keep the changelog properly updated

chore: Reconstruct changelog

---

package.json
yarn.lock

Update mockttp
Older version of mockttp depended on some insecure packages

chore: Bump mockttp version

---

package.json
src/internal/superjson/schema.ts
src/internal/superjson/superjson.test.ts
src/internal/superjson/superjson.ts
tsconfig.json
yarn.lock

Creates a function to get a subset of super.json to send with metrics. Reworks config hash function to work with this subset.
We need to send the subset to backend with metrics.

feat: Rework config hash and add anonymization

---

.gitignore
CHANGELOG.md
src/client/failure/policies.test.ts
src/client/failure/policies.ts
src/client/failure/policy.ts
src/client/failure/resolution.ts
src/lib/backoff.test.ts
src/lib/backoff.ts

Initial draft of failure policy
Eventually we can use composition to build up more complex policies and also let users to do the same if they wish to have a custom policy

feat: failure policy design

---

src/client/profile-provider.test.ts
src/internal/superjson/normalize.ts
src/internal/superjson/schema.ts
src/internal/superjson/superjson.test.ts
src/lib/env.test.ts
src/lib/env.ts

This PR add retryPolicy configuration to super.json

feat: retry policy

---

src/client/failure/event-adapter-typed.test.ts
src/client/failure/event-adapter.test.ts
src/client/failure/policies.test.ts
src/client/failure/policies.ts
src/client/usecase.ts

This PR disables provider failover when user specifies provider

feat: disable failover on user specified provider

---

src/client/failure/event-adapter-typed.test.ts
src/client/failure/event-adapter.test.ts
src/client/failure/policies.test.ts
src/client/failure/policies.ts
src/client/usecase.ts

This PR add switching providers on before execution

feat: switch providers in before execution

---

CHANGELOG.md
src/client/client.ts
src/client/failure/event-adapter-typed.test.ts
src/client/failure/event-adapter.test.ts
src/client/failure/policies.test.ts
src/client/failure/policies.ts
src/client/usecase.ts
src/internal/superjson/normalize.ts

Hook context was being recreated for each UseCase instance, now it is not.

feat: preserve hook context between usecase instances

---

src/internal/superjson/mutate.ts
src/internal/superjson/superjson.test.ts

This PR fixes missing resolution for cases with existing profile without defaults object.

fix: profile defaults

---

src/internal/superjson/mutate.ts
src/internal/superjson/superjson.test.ts

This PR fixes problems with priority and defaults resolution when adding new profile provider

fix: profile provider mutate

---

src/client/failure/event-adapter-typed.test.ts
src/client/failure/event-adapter.test.ts
src/client/failure/event-adapter.ts
src/client/failure/policies.test.ts
src/client/failure/policies.ts
src/client/failure/policy.ts

This PR adds formatFailureReason function to enable passing error thru Retry and Abort policy

chore: pass request error thru policy

---

src/client/failure/event-adapter.test.ts
src/client/failure/policy.ts

This PR fixes wrong import - I forgot to merge main before margin PR :/

fix: wrong import

---

CHANGELOG.md
src/client/client.ts
src/client/failure/event-adapter.ts
src/client/failure/policies.ts
src/client/profile-provider.test.ts
src/client/profile-provider.ts
src/client/profile.test.ts
src/client/profile.ts
src/client/registry.test.ts
src/client/registry.ts
src/internal/errors.helpers.ts
src/internal/interpreter/http/http.ts
src/internal/interpreter/http/security.ts
src/internal/interpreter/profile-parameter-validator.errors.ts
src/internal/interpreter/profile-parameter-validator.ts
src/internal/interpreter/variables.ts
src/internal/superjson/mutate.ts
src/internal/superjson/normalize.ts
src/internal/superjson/superjson.test.ts
src/internal/superjson/superjson.ts
src/lib/events.ts
src/lib/object.ts

Make every `throw` use an Error subclass
We want Errors to be more descriptive, before this some errors threw plain Error or even just string

feat: Use Error subclasses

---

package.json
yarn.lock

This PR moves ESLint packages to devDependencies and updates them from 4.27.0 to 4.29.0.
Install dev dependencies on production in unnecessary.

Move ESLint packages to devDependencies

---

CHANGELOG.md
src/client/client.test.ts
src/client/client.ts
src/client/failure/event-adapter.ts
src/client/profile-provider.test.ts
src/client/profile-provider.ts
src/client/provider.test.ts
src/client/provider.ts
src/client/registry.test.ts
src/client/registry.ts
src/client/usecase.test.ts
src/config.test.ts
src/config.ts
src/internal/superjson/superjson.ts
src/lib/reporter.test.ts
src/lib/reporter.ts

It is now implemented to fetch provider info when a map is local.
Previously it wasn't implemented.

feat: fetch provider info when map is local

---

CHANGELOG.md
src/internal/superjson/mutate.ts
src/internal/superjson/superjson.mutate.test.ts
src/internal/superjson/superjson.ts

SuperJson mutate set methods
Set methods allow both deletion and overwriting of profiles, profile providers and providers

feat: superjson mutate set methods

---

CHANGELOG.md
src/internal/index.ts

Exports `ErrorBase`, `SDKExecutionError` and `UnexpectedError` from internal module. 
Mocking in testing library tests.

feat: Export errors from internal module

---

CHANGELOG.md
src/client/profile-provider.test.ts
src/client/profile-provider.ts
src/internal/errors.helpers.ts

Validates whether provider name matches across super.json, provider.json and map file
If they are not validated, there can be security implications and misleading error messages

fix: Validate provider names

---

CHANGELOG.md
src/client/index.ts

Exports `PerformError` from client module.
Need to clean up recordings before perform throws error. See [this commit](https://github.com/superfaceai/testing-lib/pull/1/commits/dd180d2a58bc258e227945ada836e2733ebc61be) in testing library PR.

feat: Export PerformError from client module

---

src/lib/fetch.test.ts
src/lib/fetch.ts

This PR adds support for binary content types in http response.
Support for binary content types is required by speech synthesis use-case. See speech synthesis [Station PR](https://github.com/superfaceai/station/pull/21). IBM cloud provider response contains binary content type - [IBM API docs](https://cloud.ibm.com/apidocs/text-to-speech#synthesize-response).

Add support for binary content types

---

CHANGELOG.md
src/client/client.test.ts
src/client/client.ts

Fixes priority resolution
Priority array was not used correctly to resolve priorities

fix: Resolve priority correctly

---

CHANGELOG.md
package.json
src/client/profile-provider.ts

Makes `configuration` of `BoundProfileProvider` public.
Need to access security schemes from provider.json in testing library.

feat: Make configuration of BoundProfileProvider public

---

src/internal/parser.test.ts
src/internal/parser.ts

This PR adds check to Parser class clearCache function. Now file cache is deleted only if it actually exists.

fix: clear cache only if it exists

---

src/client/registry.ts

Uses new format of backend's provider response
We need to use the new response, or it would break, obviously

chore: Use nested provider response

---

src/lib/object.test.ts

This PR refactors object `clone` tests.
Better tests readability. Proposed in https://github.com/superfaceai/one-sdk-js/pull/175

Use Jest's built-in expectation in object `clone` tests

---

CHANGELOG.md
src/internal/interpreter/variables.test.ts
src/internal/interpreter/variables.ts

Removes `undefined` values in variablesToStrings function
`undefined` values should not be preserved as strings

fix: Remove undefined when stringifying

---

README.md

Removes section about typed sdk from README
Typed SDK is not ready for use yet

chore: Remove typed section from README

---

CHANGELOG.md

Adds missing changelog entry
Followup on https://github.com/superfaceai/one-sdk-js/pull/180

Add body json pointer to changelog

---

.github/workflows/main.yml
.github/workflows/release.yml

Setups test CI/CD workflow to test One SDK with Nodej.js LTS (16) and latest (18).
On October 26th [Node.js 16.13.0 became active LTS](https://nodejs.org/en/blog/release/v16.13.0/) and so we should be sure it will work on current LTS.
I am actually thinking about adding all active versions ([12, 14, 16, 17](https://nodejs.org/en/about/releases/)).

Test with Node.js LTS and latest

---

.github/pull_request_template.md
CONTRIBUTING.md
README.md
SECURITY.md

- Replaced mentions of "Superface SDK" with "OneSDK" or "Superface OneSDK"
- Simplified README, removed most of the SDK-specific docs in favor of linking to documentation
- Some specific explanations, like working with results object and environment variables are missing now; I will move them to docs.
- Renamed CONTRIBUTION_GUIDE to CONTRIBUTING since that's file recognized by GitHub
- Updated CONTRIBUTING guide
- Removed ToC since the whole README is short enough; also, broke away from Standard Readme, I don't think it's suitable for projects.
- Added direct links to SF website, docs, Discord, and repeated them a lot in the README just in case someone missed it.
For reference, I was inspired by recommendations and featured projects in [this …

docs: Simplify and update README, CONTRIBUTING and others

---

CHANGELOG.md
src/client/client.integration.test.ts
src/client/client.ts
src/client/profile-provider.ts
src/client/usecase.test.ts
src/client/usecase.ts

Allows overriding integration parameters in perform call
This allows us to configure specific calls at runtime, like per-user configuration

feat: Allow passing parameters to perform

---

CHANGELOG.md

Add missing chagelog entry for v1.2.1.

chore(changelog): Add release note for 1.2.1

---

.github/workflows/main.yml
.github/workflows/release.yml
package.json
scripts/check_dependencies.js

- prevent non-prereleases from non-main branches
- prevent merging with prerelease dependencies

chore: Add stupidity checks to CI

---

.github/workflows/release.yml

After publishing new release (not pre or rc), it will trigger workflow of https://github.com/superfaceai/superface-daily to verify nothing broke.
To automate what we do anyway.

Trigger daily test after publishing new release

---

package.json
src/internal/interpreter/sandbox.test.ts
yarn.lock

Update [vm2](https://security.snyk.io/vuln/SNYK-JS-VM2-2309905) and [node-fetch](https://security.snyk.io/vuln/SNYK-JS-NODEFETCH-2342118) to address vulnerability issues.
It changes test checking unavailability of `import` which behaviour was changed in https://github.com/patriksimek/vm2/pull/377. Vm2 changed how import is checked, and this [construct](https://github.com/superfaceai/one-sdk-js/blob/dev/src/internal/interpreter/sandbox.ts#L64) was invalid, but now import isn't caught, but the code is invalid and isn't passing tokenization as it looked as `use strict';const vmResult = import fs; fs.readFileSync("secrets");vmResult`.
vm2 and node-fetch has reported high severity vulnerability issue. We don't want have those in our dependency chain.

Update vm2 and node-fetch to address vulnerability issues

---

CHANGELOG.md
src/internal/interpreter/map-interpreter.test.ts
src/internal/interpreter/map-interpreter.ts
src/internal/interpreter/variables.ts

Iteration variable is overwritten instead of merged in each iteration
Buffer is considered primitive (same as array)
fixes #214
fixes #215

fix #214 and #215

---

CHANGELOG.md
package.json
src/client/client.test.ts
src/client/client.ts
src/client/usecase.test.ts
src/client/usecase.ts

Release 1.5.0

---

CHANGELOG.md
package.json

Merge main back to dev

---

package.json

Update package.json with relevant infromation to improve npm search
We want OneSDK to be easy to find.

Update description, add keywords abd homepage and bugs

---

src/core/usecase/usecase.test.ts
src/core/usecase/usecase.ts

This PR adds ability to pass security value (to perform call) in form of object (with id as a key). This object is resolved to SecurityValue array. This change will allow us to do security passing more user friendly while keeping it backwards compatible.

feat: resolve passed security values

---

src/core/config/config.test.ts
src/core/config/config.ts
src/core/events/reporter/reporter.test.ts
src/core/events/reporter/reporter.ts
src/node/client/client.ts

This PR enables passing IConfig variables through SuperfaceClient constructor. These values are merged with config loaded from environment. Value passed in code has higher priority. Properties like `debug` will be added in separate PR.

feat: in code config

---

CHANGELOG.md
src/core/config/config.test.ts
src/core/config/config.ts
src/core/interfaces/config.ts
src/node/client/client.ts

This PR adds debug property to SuperfaceClient constructor. This property can be used  to enable logging.

feat: debug property

---

src/core/errors/errors.helpers.ts
src/core/registry/registry.test.ts
src/core/registry/registry.ts

This PR fixes missing error handling when getting profile ast.

fix: missing error handling

---

src/core/config/config.ts

This PR changes default cache path to `node_modules/.cache/superface`.

feat: new default cache path

---

README.md
SECURITY.md

This PR updates README to document new flow.

chore: readme update

---

src/core/events/events.test.ts
src/core/events/failure/map-interpreter-adapter.ts
src/core/events/failure/policies.ts
src/core/interpreter/http/filters.ts
src/core/interpreter/http/http.test.ts
src/core/interpreter/http/http.ts
src/core/interpreter/http/security/api-key/api-key.ts
src/core/interpreter/http/security/digest/digest.test.ts
src/core/interpreter/http/security/digest/digest.ts
src/core/interpreter/http/security/http/http.ts
src/core/interpreter/http/utils.ts
src/core/interpreter/map-interpreter.ts
src/core/interpreter/profile-parameter-validator.ts
src/core/profile-provider/bound-profile-provider.test.ts
src/core/profile-provider/security.test.ts
src/core/profile-provider/security.ts
src/core/provider/resolve-provider.ts
src/lib/variables/variables.test.ts
src/node/fetch/fetch.node.ts

chore: format code

---

src/core/profile-provider/profile-provider.ts
src/core/profile/cache-profile-ast.test.ts
src/core/profile/cache-profile-ast.ts
src/core/profile/resolve-profile-ast.test.ts
src/core/profile/resolve-profile-ast.ts

This PR fixes missing dirname in profile, map and provider file resolution and aligns profile caching with: 
https://www.notion.so/superface/Caching-in-SDK-2-0-0-afee3996e7be476982bb4bd599c2a587

fix: file resolution

---

src/core/profile-provider/profile-provider.ts

This PR removes .suma extension from map file resolution. I am not happy with this part of code and I suggest resolving: https://github.com/superfaceai/one-sdk-js/issues/279 to fix it. But now (for 2.0.0) I don't want to change this (critical) part of code. So I just removed extension that is not supported.

fix: remove unsupported map extension

---

.github/workflows/main.yml
src/core/config/config.test.ts

This updates Node.js versions in build matrix to [currently supported Node.js versions](https://nodejs.org/en/about/releases/): v14 (EOL April 2023), v16 and v18. v17 is not supported anymore.
This is a follow-up to #187.
We should be able to guarantee compatibility with currently supported Node.js versions.

chore(ci): Run tests on Node.js 14, 16, 18

---

README.md

This PR adds mention of what is considered public api to readme. Wording sucks, because it's Friday 😅

chore: public api in readme

---

CHANGELOG.md

Fixes duplicate `fixed` section in changelog.
I missed it #297 as it was collapsed.

Fix section in changelog

---

CHANGELOG.md

chore: forgot to update changelog again

---

README.md

Updates the URL of GitHub workflow status badge to accommodate for breaking changes in https://github.com/badges/shields/issues/8671

chore(README): Fix GH workflow badge URL

---

src/core/interpreter/http/http.ts

Fixes kind for query and header validation

Query validation error message had swapped kind

---

package.json
src/core/interpreter/profile-parameter-validator.ts
yarn.lock

Uses AST and Parser which contains None.
We want to use Parser and AST with latest functionality.

Update ast and parser containing None changes

---

src/node/client/client.ts
src/node/index.ts
src/node/sandbox/index.ts

This PR exports NodeSandbox from node module, to allow use in testing library.
NodeSandbox is needed in testing library to instantiate bound profile provider.

Export NodeSandbox from node module
