- src/client/profile-provider.test.ts
- src/internal/superjson/normalize.ts
- src/internal/superjson/schema.ts
- src/internal/superjson/superjson.test.ts
This PR removes `onFail` property from `retryPolicy`
> feat: remove onFail property

- src/internal/superjson/mutate.ts
- src/internal/superjson/superjson.test.ts
This PR fixes problem with wrong profile provider defaults normalization and missing priority resolution
> fix: add profile defaults resolution

- src/internal/superjson/mutate.ts
- src/internal/superjson/superjson.test.ts
- src/internal/superjson/superjson.ts
This PR adds function to mutate profile defaults in super json
> feat: mutate profile defaults

- CHANGELOG.md
- package.json
- src/client/failure/event-adapter.ts
- src/internal/errors.test.ts
- src/internal/errors.ts
- src/internal/interpreter/map-interpreter.errors.test.ts
- src/internal/interpreter/map-interpreter.errors.ts
- src/lib/fetch.errors.ts
- src/lib/fetch.test.ts
- src/lib/fetch.ts
Add `toString()` methods to error classes that don't contain this method.
Error formatting.
> feat: Add toString() methods to errors

- package.json
- src/client/failure/event-adapter.test.ts
- yarn.lock
Adds tests that catch wrong hook context persistence:
Across one client hooks should be preserved
Across multiple clients hooks should not be preserved
> feat: add hook context persistence tests

- src/client/profile-provider.test.ts
- src/client/profile-provider.ts
- src/internal/errors.helpers.ts
This PR adds throwing error in cases when user has local provider and remote map.
> feat: throw error on local provider and remote map

- CHANGELOG.md
- src/client/failure/event-adapter.ts
- src/client/failure/policy.ts
- src/client/usecase.ts
- src/lib/fetch.errors.ts
- src/lib/reporter.ts
Pass unknown errors from fetch down the failover machinery
Failover machinery was not prepared for non-network/request errors from fetch and mostly ate the error. This allows it to be shown at least
> fix(failover): Pass unknown errors from fetch

- CHANGELOG.md
- package.json
- src/client/client.test.ts
- src/internal/interpreter/map-interpreter.test.ts
- src/internal/interpreter/map-interpreter.ts
- src/internal/parser.test.ts
- src/internal/superjson/superjson.test.ts
- yarn.lock
Awaiting resolution on whether to preserve result object merging:
```
map Test {
map result { a = 41 }
map result { b = 42 }
}
// Should this return { a: 41, b: 42 } or { b: 42 }?
```
* removed unnecessary result propagation from interpreter
* terminal outcome statements in interation now correctly break the iteration
Sdk didn't correctly break from iteration before
> fix: call-foreach early termination

- CHANGELOG.md
- src/client/registry.test.ts
- src/client/registry.ts
- src/internal/interpreter/http/http.test.ts
- src/internal/interpreter/http/http.ts
- src/internal/interpreter/map-interpreter.errors.test.ts
- src/internal/interpreter/map-interpreter.test.ts
- src/internal/interpreter/map-interpreter.ts
- src/lib/reporter.test.ts
This PR fixes two issues:
- it requires baseUrl to be specified for HTTP calls in map, as absolute URLs are no longer supported
- path parameter interpolation does not work on base URLs, only the relative path in map
For security reasons, we need to only use base URL from provider.json and not allow interpolating it.
> fix: Forbid absolute URLs in map

- CHANGELOG.md
- src/client/client.ts
Marks cacheBoundProfileProvider as deprecated
This function should not have been a part of Client's public interface as it's not intended for consumer use
> chore: Mark cacheBoundProfileProvider deprecated

- CHANGELOG.md
- src/internal/interpreter/map-interpreter.errors.test.ts
- src/internal/interpreter/map-interpreter.ts
- also throw on inline call failure
- pass errors through operation call levels
- also throw on inline call failure
Errors were not passed through multiple levels and inline call failures should not happen
> fix: Pass errors through operation call levels

- src/lib/object.test.ts
- src/lib/object.ts
This PR fixes `Buffer` and `Date` cloning
ONESDK clones fetch params. If there is `Buffer` instance in body fetch parameter it is cloned as `Object` without prototype. Fetch then serialises the object as `[object Object]`.
This PR uses recursion to traverse over object properties and depending on the property type creates deep copy of it.
> Fix Buffer and Date cloning

- CHANGELOG.md
- src/internal/interpreter/map-interpreter.errors.test.ts
- src/internal/interpreter/profile-parameter-validator.test.ts
- src/internal/interpreter/profile-parameter-validator.ts
Changes ProfileParameterValidator behavior to resolve NamedModels before field references.
When the field references were resolved before named models, the model definitions were not found, thus crashing the validator.
> fix(ProfileParameterValidator): Resolve NamedModels first

- src/internal/errors.helpers.ts
- src/internal/interpreter/http/security.test.ts
- src/internal/interpreter/http/security.ts
This PR allows to use `/` to specify nested location of apikey in JSON body.
It uses same syntax as JSON Poniter, but it doesn't allow to work with arrays.
Implements https://github.com/superfaceai/one-sdk-js/issues/176
Some APIs have api tokens deeper in body payload. eg https://github.com/superfaceai/station/pull/158
> Allow to use / in name to specify apikey location in body

- CHANGELOG.md
- src/config.ts
- src/internal/interpreter/sandbox.ts
Makes sandbox timeout configurable through an environment variable
AWS lambda functions time out with the default timeout for some reason, this is a quick way to fix it in the meantime and also it's good to have it configurable anyway
> feat: make sandbox timeout configurabe through an env variable

- CHANGELOG.md
- src/internal/interpreter/sandbox/index.ts
- src/internal/interpreter/sandbox/sandbox.test.ts
- src/internal/interpreter/sandbox/sandbox.ts
- src/internal/interpreter/sandbox/stdlib.ts
- src/lib/object.ts
Adds an inital stdlib available to script sandbox. Currently only `unstable` symbols.
Need to have at least some support for ISO date <-> unix timestamp conversion
> feat: add initial unstable stdlib to sandbox

- src/client/profile.test.ts
- src/client/profile.ts
This PR adds getConfiguredProviders function for getting providers(maps) configured for current profile.
https://github.com/superfaceai/one-sdk-js/issues/211
> feat: get configured providers

- CHANGELOG.md
- package.json
- src/internal/interpreter/http/http.ts
- src/internal/interpreter/http/security/apiKey/api-key.test.ts
- src/internal/interpreter/http/security/apiKey/api-key.ts
- src/internal/interpreter/http/security/interfaces.ts
- src/internal/interpreter/map-interpreter.ts
Fixes an issue where authentication deleted existing query parameters
Query parameters were deleted, which was sad, because I needed them for my usecase
> fix: Preserve query in auth

- CHANGELOG.md
- src/internal/interpreter/http/http.test.ts
- src/internal/interpreter/http/http.ts
- src/internal/interpreter/map-interpreter.test.ts
- src/internal/interpreter/variables.ts
Rewritten `replaceParameters` using the newer `String.matchAll` api while taking care of whitespace. I believe this makes the method more readable as well.
Fixes #228
> fix: http::replaceParameters now trims whitespace

- CHANGELOG.md
- src/client/failure/event-adapter.test.ts
- src/client/registry.test.ts
- src/internal/errors.helpers.ts
- src/internal/interpreter/http/http.ts
- src/internal/interpreter/sandbox/sandbox.test.ts
- src/internal/interpreter/sandbox/sandbox.ts
- src/internal/interpreter/variables.ts
Does a fixup of values coming out of the sandbox for display purposes - but only for the debug right there in the function, not globally.
fix #16
> fix: attempt at fixing vm2 proxy weirdness with arrays

- src/internal/interpreter/sandbox/sandbox.ts
Preserves ArrayBuffer in vm2 fixup
We need it so it is preserved
> fix: Preserve ArrayBuffer in vm2fixup

- CHANGELOG.md
- src/internal/interpreter/http/filters.test.ts
- src/internal/interpreter/http/filters.ts
- src/internal/interpreter/http/http.test.ts
Related to #230 (but not root cause).
When I want to send body with `multipart/form-data` encoding to Mailgun, I am getting back server error "Missing content boundary". Upon closer inspection, the [boundary directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type#directives) is missing in the `Content-Type` header. It is normally automatically read from `FormData`, but since `content-type` is set explicitly, it's not overwritten.
Thanks to @lukas-valenta for helping me to solve this issue.
> fix(http): Don't set content-type w/ form-data

- CHANGELOG.md
- src/client/provider.test.ts
- src/client/provider.ts
Changes ProviderConfiguration cache key so it doesn't get recached on security change
With the addition of passing security values in runtime, we don't want to rebind on every change
> fix: Do not recache ProviderConfig on security change

- CHANGELOG.md
- src/client/client.test.ts
- src/client/client.ts
- src/client/failure/event-adapter.test.ts
- src/client/profile-provider.test.ts
- src/client/profile-provider.ts
- src/client/provider.test.ts
- src/client/provider.ts
- src/client/usecase.test.ts
- src/client/usecase.ts
- src/internal/interpreter/map-interpreter.ts
- src/lib/events.test.ts
- src/lib/reporter.test.ts
This PR refactors passing of security through perform. It removes security from bind, now passed security is used directly in perform.
> chore: refactor security passing through perform

- CHANGELOG.md
- src/client/profile-provider.ts
Moves `Config.instance()` out of global scope - this was instantiating the global singleton during importing of the module, which prevented `process.env` modification in the importing module from having the intended effect.
This will be fixed again by #236 
Bug #235
> fix: move Config.instance() call out of global scope

- CHANGELOG.md
- src/core/config/config.ts
- src/core/interfaces/config.ts
- src/core/parser/parser.test.ts
- src/core/parser/parser.ts
- src/core/profile-provider/profile-provider.test.ts
- src/core/profile-provider/profile-provider.ts
- src/node/client/client.ts
This PR adds `cache` property to SuperfaceClient constructor. This property can be used to disable caching (mam and profile AST and provider.json) to filesystem.
> feat: cache property

- CHANGELOG.md
- src/core/client/client.internal.ts
- src/core/errors/errors.helpers.ts
- src/core/events/failure/event-adapter.test.ts
- src/core/events/reporter/reporter.test.ts
- src/core/profile-provider/profile-provider.test.ts
- src/core/profile-provider/profile-provider.ts
- src/core/profile/index.ts
- src/core/profile/profile.test.ts
- src/core/profile/profile.ts
- src/core/profile/profile.typed.test.ts
- src/core/profile/profile.typed.ts
- src/core/profile/resolve-profile-ast.test.ts
- src/core/profile/resolve-profile-ast.ts
- src/core/registry/registry.test.ts
- src/core/registry/registry.ts
- src/core/usecase/usecase.test.ts
- src/core/usecase/usecase.ts
- src/lib/utils/utils.ts
- src/mock/client.ts
- src/mock/filesystem.ts
- src/mock/index.ts
- src/mock/profile-document-node.ts
- src/node/client/client.integration.test.ts
- src/node/client/client.test.ts
- src/node/client/client.typed.ts
This PR add ability to load profile remotely without CLI installation. It moves profile resolution to `getProfile` method and adds check to ensure that use case exists in profile AST.
> feat: early remote profile resolution

- CHANGELOG.md
- src/core/client/client.internal.test.ts
- src/core/client/client.internal.ts
- src/core/config/config.ts
- src/core/errors/errors.helpers.ts
- src/core/interfaces/client.ts
- src/core/profile/resolve-profile-ast.test.ts
- src/core/profile/resolve-profile-ast.ts
- src/mock/client.ts
- src/node/client/client.ts
- src/node/client/client.typed.ts
This PR adds option to pass version to `getProfile` method as part of the profileId string. Optionally, id and version can be passed as object. Passed id and version is used during profile ast resolution.
Caching of profile ast and use without any super.json will be done in separate PRs
> feat: pass version to get profile

- CHANGELOG.md
- src/core/interfaces/client.ts
- src/core/profile-provider/profile-provider.test.ts
- src/core/profile-provider/profile-provider.ts
- src/core/profile/profile.test.ts
- src/core/provider/provider.ts
- src/core/usecase/usecase.test.ts
- src/core/usecase/usecase.ts
- src/mock/client.ts
- src/node/client/client.test.ts
- src/node/client/client.ts
- src/schema-tools/superjson/utils.test.ts
- src/schema-tools/superjson/utils.ts
This PR adds option to pass `security` and `parameters` to `getProvider` method. Passed values are used in perform (if not overridden by values passed directly to perform)
> feat: get provider options

- src/core/profile/resolve-profile-ast.ts
This PR fixes problem with passing incorrect version to caching helper.
> fix: pass correct version to cache helper

- src/core/errors/errors.helpers.ts
- src/mock/client.ts
- src/node/client/client.test.ts
- src/node/client/client.ts
This PR adds throwing of error when `getProviderForProfile` is called on client without SuperJson
> feat: get provider for profile error

- src/core/profile-provider/bound-profile-provider.ts
- src/core/profile-provider/parameters.test.ts
- src/core/profile-provider/parameters.ts
- src/core/profile-provider/profile-provider.ts
This PR fixes problem with not resolving(checkong) integration parameters passed directly to perform.
Utility function for parameter resolution has been moved to separate file and is called during bind and perform. This is similar to security values resolution.
> fix: integration parameters resolution

- src/core/events/reporter/reporter.test.ts
- src/core/events/reporter/reporter.ts
- src/mock/client.ts
- src/node/client/client.test.ts
- src/node/client/client.ts
Setting up metrics reporting without super.json and changing super.json to be uptional for MetricReporter instance.
Client will skip `SDKInit` event reporting if super.json is not present.
This requires changes in backend services, which are done in https://github.com/superfaceai/brain/pull/434
We want reporting of performs even without super.json.
But SDKInit doesn't need to be send as it doesn't have any value.
> Metrics reporting without super.json

- CHANGELOG.md
- src/core/interpreter/http/filters.test.ts
- src/core/interpreter/http/filters.ts
- src/core/interpreter/http/utils.ts
- src/core/interpreter/map-interpreter.ts
Do not set `accept` header when defined in [HTTP request headers](https://spec.superface.dev/latest/map-spec.html#HTTPHeaders). I wanted to normalize headers and work with them, but that could lead to unexpected behavior and better will be to allow set as many headers and in any case. It will delegate need to normalize to client and server.
One thing I am not happy about, is how the logic is split in `map-interpreter` and `filters`. 
Fixes #264
> Fix for resolving accept header

- CHANGELOG.md
- package.json
- src/core/interpreter/http/filters.ts
- src/core/interpreter/http/interfaces.ts
- src/node/fetch/fetch.node.test.ts
- src/node/fetch/fetch.node.ts
- yarn.lock
This PR fixes handling Buffers in `multipart/form-data`. It also adds support to duplicate fields by allowing define array as value.
Switched from `isomorphic-form-data` to `form-data`, which handles buffers correctly.
Also, I had to fix `fetch.node.test.ts` where the mocking wasn't working as expected. https://github.com/superfaceai/one-sdk-js/pull/292/commits/6c193a8ed0fd65779475c4830c8e426d01749b9b
Fixes #291
> Fix handling Buffers in `multipart/form-data`

- CHANGELOG.md
- src/node/fetch/fetch.node.test.ts
- src/node/fetch/fetch.node.ts
Added function to format Record to array of tuples which is expected in `HeadersInit` and support duplicate headers.
The original test is indented, so it looks long. So, check it with [hidden whitespaces](https://github.com/superfaceai/one-sdk-js/pull/293/files?diff=split&w=1).
TypeScript compiler was complaining about the shape of `headersInit` data.
> Shape HeadersInit from FetchParameters

- CHANGELOG.md
- src/core/interpreter/http/filters.ts
- src/core/interpreter/http/http.test.ts
- src/core/interpreter/http/utils.test.ts
- src/core/interpreter/http/utils.ts
Added set of helper functions to work with headers in interpreter.
Best would be to switch to [Headers](https://developer.mozilla.org/en-US/docs/Web/API/Headers) which isn't available for not until 18.0.0. But I wanted to avoid bigger refactoring and implementing own Headers class.
In #290 was fixed how accept header is set. This extends it to entire  `headersFilter`.
> Fix for headers handling in filters

- CHANGELOG.md
- src/core/interpreter/http/utils.test.ts
- src/core/interpreter/http/utils.ts
- src/core/interpreter/map-interpreter.test.ts
The following map was returning an error about the url not being relative, even though it is considered relative to the base url and should work.
```
http GET '/' {}
```
Bug reported through Slack
> fix(interpreter): `/` url will not error as absolute

- src/core/interpreter/map-interpreter.test.ts
- src/core/interpreter/sandbox/stdlib.ts
- src/node/filesystem/binary.node.test.ts
- src/node/filesystem/binary.node.ts
- src/node/filesystem/index.ts
- adds `name` and `mimetype` to `fromStream` factory function
- adds setters on `BinaryData` for `name` and `mimetype`
```
map Example {
// need to do comlink variable assign to be able to use Script expression
tmp = (input.file.name = input.filename)
tmp = (input.file.mimetype = input.mimetype)
http POST "/" {
request "multipart/form-data" {
body = {
file: input.file
}
}
response 200 {
map result body
}
}
}
```
Comlink author may need to set mimetype or name from within the map.
> Allow setting binary data metadata

- src/core/interpreter/map-interpreter.test.ts
- src/core/interpreter/map-interpreter.ts
- src/node/client/client.integration.test.ts
This PR contains a fix to handling input value being `null` as well, one of the values in mapped outcome is `null`.
Types should be fixed after #295 
Station tests are passing now:
Examples:
- [null in result](https://github.com/superfaceai/station/blob/main/grid/crm/contacts/maps/sendgrid.suma#L28)
- [null passed as input](https://github.com/superfaceai/station/blob/main/grid/social-media/posts/maps/linkedin.test.ts#L38)
> Nulls where not expected by types

- src/core/errors/errors.helpers.ts
- src/core/interpreter/http/filters.ts
- src/core/interpreter/http/http.ts
- src/core/interpreter/http/interfaces.ts
- src/core/interpreter/http/security/api-key/api-key.ts
- src/core/interpreter/http/security/digest/digest.ts
- src/core/interpreter/http/security/http/http.ts
- src/core/interpreter/http/security/interfaces.ts
- src/core/interpreter/http/utils.test.ts
- src/core/interpreter/http/utils.ts
- src/core/interpreter/map-interpreter.errors.test.ts
- src/core/interpreter/map-interpreter.errors.ts
- src/core/interpreter/map-interpreter.test.ts
- src/core/interpreter/map-interpreter.ts
- src/interfaces/errors/map-interpreter.errors.ts
- src/lib/object/object.test.ts
- src/lib/object/object.ts
- src/lib/variables/variables.ts
- src/node/fetch/fetch.node.ts
Good news: Tests now compile and all map interpreter tests pass, no less tests pass than in base. Verified by quickly cooking up a differ[0] and checking `jest --json --outputFile tests.json` on the base branch vs. this branch (`python3 differ.py tests1.json tests2.json`).
This contains two BREAKING CHANGEs:
* rejects values passed to headers and query parameters which aren't `string | string[]`, instead telling the user to stringify them themselves before use
- Relaxed for booleans and numbers, which are stringified by the implementation.
* does not even set `input` nor `parameter` in interpreter if they are passed in as `undefined` or `null` (although with null it is an invalid use of the perform API).
- This means the map will fail at runtime (jessie error) if you try to access `input` …
> feat: ensure None type behaves correctly

- src/core/interpreter/map-interpreter.test.ts
- src/core/profile-provider/bound-profile-provider.ts
- src/core/registry/registry.test.ts
- src/schema-tools/superjson/mutate.ts
- src/schema-tools/superjson/normalize.ts
- handling `undefined` before passed to `castToNonPrimitive`
- commented out test for duplicate/multi-valie headers, which should be done as part of #324 
- fixed tests asserting old header format in registry calls
We want to have passing tests, so we can do beta release
> Fixes remaining issues for None type

- src/core/interpreter/http/interfaces.ts
- src/core/interpreter/http/security/digest/digest.ts
- src/core/interpreter/http/types.ts
- src/core/interpreter/map-interpreter.errors.ts
- src/core/interpreter/map-interpreter.test.ts
- src/node/fetch/fetch.node.test.ts
- src/node/fetch/fetch.node.ts
This applies on top of #323. It was supposed to fix multi-valued response headers, but it seems we are blocked by node-fetch and upgrading it to 3.x version isn't trivial, so for now only these changes.
I'm setting the base to #323 for the diff to be meaningful, but it should be changed to `dev` later, I suppose.
> Multi-valued response headers as multimap

- CHANGELOG.md
- src/core/interpreter/sandbox/sandbox.test.ts
- src/core/interpreter/sandbox/sandbox.ts
Safer sandbox, but better eval expression.
Potentially this could break Comlink Script expression's evaluation.
> Trailing comment in sandbox expression shouldn't breake it

- CHANGELOG.md
- src/node/fetch/fetch.node.test.ts
- src/node/fetch/fetch.node.ts
Skip body handling for 204 responses
Some server may return `Content-Type: application/json` header, but don't send any body.
This leads to failed JSON.parse.
> Ignore body when 204 response status received

- CHANGELOG.md
- src/lib/variables/variables.test.ts
- src/lib/variables/variables.ts
We can get inputs from users with inputs created using `Object.create(null)` so they have no constructor.
> Objects can be without prototype and thus constructor

- CHANGELOG.md
- src/core/events/reporter/reporter.test.ts
- src/core/interpreter/profile-parameter-validator.test.ts
- src/core/interpreter/profile-parameter-validator.ts
This adds proper validation of input and it emulates  inputs based on presence in profile.
This is temporary fix as the best is to wrap input structure to NoneNull already in parser. Which I will do in next iteration.
Also I needed to change passed values in one test which did pass object even though nothing should be passed. Exactly we are doing this change. To make clearer what is validated.
> Input validation to work with None values

- src/core/profile-provider/resolve-map-ast.test.ts
- src/core/profile-provider/resolve-map-ast.ts
- src/core/profile/resolve-profile-ast.test.ts
- src/core/profile/resolve-profile-ast.ts
- src/core/provider/resolve-provider-json.test.ts
- src/core/provider/resolve-provider-json.ts
- src/lib/utils/utils.ts
Goal is to be able to pass ASTs directly in super.json. See example bellow.
Eventually I will add `ast` to [SuperJson](https://github.com/superfaceai/ast-js/tree/main/src/interfaces/superjson), but for internal use this should be sufficient. 
```ts
import type { SuperJsonDocument } from '@superfaceai/ast';
import { readFile } from 'fs/promises';
import { resolve } from 'path';
import { SuperfaceClient } from '../node';
async function readAst(file: string): Promise<string> {
// eslint-disable-next-line @typescript-eslint/no-unsafe-return
return await readFile(resolve(__dirname, file), { encoding: 'utf8' });
}
async function main() {
const superJson: SuperJsonDocument = {
profiles: {
profile: {
ast: await readAst('./profile.supr.ast.json'),
providers: {
provider: {
ast: await …
```
> Add ast property to superjson to load profile ast, map ast and provider.json 

- src/schema-tools/superjson/normalize.test.ts
- src/schema-tools/superjson/normalize.ts
Follow up to #336 
Normalize function didn't take in account `ast` field and created normalized document without it.
> Normalize superjson preserve ast field

- CHANGELOG.md
- src/node/fetch/fetch.node.test.ts
- src/node/fetch/fetch.node.ts
Fields with value `null` or `undefined` are not sent, as they are not convertible to string or Blob.
Internally reported bug.
> Handle undefined and null in form-data field value

- CONTRIBUTING.md
- README.md
Remove and replace references to Discord in favor of GitHub Discussions and Support page.
Also update the copyright year.
> docs: Replace Discord w/ GH Discussions, update copyright year
